### ISSUE TITLE
Validation inside model do not work

### ISSUE THREAD

**Issue by gotar** [lotus/validations#44]
Using lotus-utils 0.3.3
Using sequel 4.18.0
Using lotus-model 0.2.0
Using lotus-validations 0.2.2

```ruby
require 'lotus/model'
require 'lotus/validations'

class Product
  include Lotus::Entity
  include Lotus::Validations

  attributes :name
  validates :name, type: String, presence: true
end

class ProductRepository
  include Lotus::Repository
end

Lotus::Model.configure do
  adapter type: :memory, uri: 'memory://localhost/test'

  mapping do
    collection :products do
      entity     Product
      repository ProductRepository

      attribute :id,   Integer
      attribute :name, String
    end
  end
end

Mutex.new.synchronize do
  Lotus::Model.load!
end

p = ProductRepository.create(Product.new(name: 'foo'))
r = ProductRepository.find(p.id)
ProductRepository.delete(r)

bundle exec ruby test.rb
/Users/gotar/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/lotus-validations-0.2.2/lib/lotus/validations/validation_set.rb:61:in `validate_options!': Unknown validation(s): type for "name" attribute (ArgumentError)
	from /Users/gotar/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/lotus-validations-0.2.2/lib/lotus/validations/validation_set.rb:32:in `add'
	from /Users/gotar/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/lotus-validations-0.2.2/lib/lotus/validations.rb:116:in `validates'
	from test.rb:9:in `<class:Product>'
	from test.rb:4:in `<main>'
```

**Comment by AlfonsoUceda** [comment]
another example fails:

```ruby
require 'sequel'
require 'sqlite'
require 'lotus/model'

DATABASE_URL = 'sqlite:///tmp/database.sqlite'

db = Sequel.connect(DATABASE_URL)
db.create_table! :users do
  primary_key :id
  String :name
  Integer :age
end

class User
  include Lotus::Entity
  include Lotus::Validations

  attributes :name, :age
  validates :name, type: String, presence: true
end

class UserRepository
  include Lotus::Repository
end

Lotus::Model.configure do
  adapter type: :sql, uri: DATABASE_URL

  mapping do
    collection :users do
      entity      User
      repository UserRepository

      attribute :id,   Integer
      attribute :name, String
      attribute :age,  Integer
    end
  end
end

Lotus::Model.load!

user = UserRepository.create(User.new(name: 'Alfonso', age: 27))

NoMethodError: undefined method `name' for #<User:0x000000023076e8>
    from (eval):6:in `to_record'
    from /home/alfonso/Proyectos/lotus/forks/model/lib/lotus/model/mapping/collection.rb:362:in `serialize'
    from /home/alfonso/Proyectos/lotus/forks/model/lib/lotus/model/adapters/sql/collection.rb:203:in `_serialize'
    from /home/alfonso/Proyectos/lotus/forks/model/lib/lotus/model/adapters/sql/collection.rb:58:in `insert'
    from /home/alfonso/Proyectos/lotus/forks/model/lib/lotus/model/adapters/sql/command.rb:33:in `create'
    from /home/alfonso/Proyectos/lotus/forks/model/lib/lotus/model/adapters/sql_adapter.rb:63:in `create'
    from /home/alfonso/Proyectos/lotus/forks/model/lib/lotus/repository.rb:288:in `create'
    from (irb):43
    from /home/alfonso/.rvm/rubies/ruby-2.1.5/bin/irb:11:in `<main>'
```
